CREATE TABLE `TB_CAMBIO` (
  `CAM_ID` INT(10) AUTO_INCREMENT PRIMARY KEY,
  `CAM_FROM` CHAR(3) NOT NULL,
  `CAM_TO` CHAR(3) NOT NULL,
  `CAM_CONVERSION` decimal(65,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
